GIT_URL = 'https://github.com/return42/searx'
GIT_BRANCH = 'searx-next'
ISSUE_URL = 'https://github.com/asciimoo/searx/issues'
SEARX_URL = 'https://searx.me'
DOCS_URL = 'https://return42.github.io/searx'
PUBLIC_INSTANCES = 'https://searx.space'
